[api_keys]
google_api_key = "AIzaSyB8m00MKVrUp5dyP_3cvZOdSxRPOAEVrFY"

[firebase]
apiKey = "AIzaSyAAZuWKFMv-cDBcvozmHWxkutFj0GR-D54"
authDomain = "exit-tickets-b1aa6.firebaseapp.com"
projectId = "exit-tickets-b1aa6"
storageBucket = "exit-tickets-b1aa6.firebasestorage.app"
messagingSenderId = "729109895884"
appId = "1:729109895884:web:e9a41705f92fbec9834069"
